# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 - now Marco Neumann (kalink0)
"""Metadata labels: the keys parsers (and the main window) put into a
result's metadata -- "Format", "Records", "Status", ...

A key is the label's English text and stays English everywhere in code,
tests and lookups (metadata["Format"]). Only its display is translated: the
Properties panel shows translate("MetadataLabel", key). This module marks
every label for the translation catalog; test_metadata_labels checks that
every key the code sets is listed here.

Field names defined by a file format's own spec (PDF document-info keys,
XMP and media-container tag names) are not listed: they stay as they are.
"""
from __future__ import annotations

from crush.core.issues import QT_TRANSLATE_NOOP

METADATA_LABELS = (
    QT_TRANSLATE_NOOP("MetadataLabel", "ATX warnings"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Active"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Active top ref"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Array layers"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Attachments"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Block order"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Byte order"),
    QT_TRANSLATE_NOOP("MetadataLabel", "C2PA"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Category"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Channels"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Chunks"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Cipher parameters"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Codec"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Companion files"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Companion files not loaded"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Declared payload bytes"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Decode status"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Decrypted size"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Deleted"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Depth"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Detection rule"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Display format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Duration"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Encoding"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Encrypted"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Entries"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Entries with timestamp"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Entry status"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Extension"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Faces"),
    QT_TRANSLATE_NOOP("MetadataLabel", "File format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "File size"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Files"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Filesystem"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Forensic relevance"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Format (identified)"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Format candidates"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Frames"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Header"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Header mnemonic"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Header values"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Height"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Hex offsets"),
    QT_TRANSLATE_NOOP("MetadataLabel", "JavaScript"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Journal mode"),
    QT_TRANSLATE_NOOP("MetadataLabel", "KTX warnings"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Key/value entries"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Level"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Lines not matching the format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Live"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Log format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Meta file"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Meta version"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Metadata"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Mipmaps"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Nesting"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Not decoded"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Note"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Original folder"),
    QT_TRANSLATE_NOOP("MetadataLabel", "PDF Version"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Page records"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Page size"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Pages"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Parse error"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Parse warning"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Parser support"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Payload"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Payload bytes"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Payload decoding"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Payload rendering"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Pixel format"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Platforms"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Possibly Encrypted"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Read error"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Records"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Recovered entries"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Reference"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Removed"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Revision chain"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Revisions"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Rollback journal"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Row data"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Row limit"),
    QT_TRANSLATE_NOOP("MetadataLabel", "SQL"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Sample rate"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Segments"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Sequence"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Signatures"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Size"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Source column"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Source file"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Source query"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Source row"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Source table"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Status"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Stream"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Streaming form"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Superseded"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Tables"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Tables found"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Text extraction"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Texture UUID"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Timestamp notes"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Total entries"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Total size"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Type"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Uncommitted"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Version"),
    QT_TRANSLATE_NOOP("MetadataLabel", "WAL slack"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Warnings"),
    QT_TRANSLATE_NOOP("MetadataLabel", "Width"),
    QT_TRANSLATE_NOOP("MetadataLabel", "XMP"),
)
