#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 - now Marco Neumann (kalink0)
"""Maintain crush/docs/forensic-test-coverage.md: which forensic checks exist
for each part of Crush, and which don't.

    python scripts/forensic_coverage.py build    regenerate the page
    python scripts/forensic_coverage.py check    fail if the page is out of date

The page is built from the @pytest.mark.forensic markers in crush/tests/
(category, subject, desc), read from the source -- no test runs. Subjects
and categories come from crush/tests/forensic_report.py, the same place the
audit report takes them from. test_forensic_coverage fails while the page is
out of date, so after adding or changing a forensic test just run build.

The page says what is checked, not whether it passes: that is the audit
report every release attaches.
"""
from __future__ import annotations

import argparse
import ast
import importlib.util
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
TESTS = ROOT / "crush" / "tests"
OUTPUT = ROOT / "crush" / "docs" / "forensic-test-coverage.md"
REPORT_URL = "https://kalink0.github.io/crush-forensics/audit/"

GENERATED_NOTE = (
    "<!-- Generated by `python scripts/forensic_coverage.py build` from the "
    "@pytest.mark.forensic tests -- edit the tests, not this file. -->\n"
)
NOT_TESTED = "not tested"
NOT_APPLICABLE = "n/a"


def _load_report() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "forensic_report", TESTS / "forensic_report.py"
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


report = _load_report()


@dataclass(frozen=True)
class Check:
    category: str
    subject: str
    desc: str
    path: str   # relative to the repository root, with forward slashes
    name: str   # the test function


def collect(tests_dir: Path = TESTS) -> list[Check]:
    """Every @pytest.mark.forensic test, in file and line order."""
    checks: list[Check] = []
    for path in sorted(tests_dir.rglob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        found: list[tuple[int, Check]] = []
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for deco in node.decorator_list:
                if not (isinstance(deco, ast.Call)
                        and ast.unparse(deco.func).endswith("mark.forensic")):
                    continue
                try:
                    kwargs = {k.arg: ast.literal_eval(k.value) for k in deco.keywords}
                except ValueError as exc:
                    raise ValueError(
                        f"{path.name}:{deco.lineno}: forensic marker arguments must be "
                        "plain strings"
                    ) from exc
                found.append((deco.lineno, Check(
                    category=kwargs.get("category", ""),
                    subject=kwargs.get("subject", ""),
                    desc=kwargs.get("desc", node.name),
                    path=path.relative_to(tests_dir.parent.parent).as_posix(),
                    name=node.name,
                )))
        checks.extend(check for _, check in sorted(found, key=lambda f: f[0]))
    return checks


def problems(checks: list[Check]) -> list[str]:
    """Markers whose category or subject isn't one of the known ones."""
    out = []
    for c in checks:
        if c.category not in report.CATEGORY_ORDER:
            out.append(f"{c.path}::{c.name}: unknown category {c.category!r}")
        if c.subject not in report.SUBJECTS:
            out.append(f"{c.path}::{c.name}: unknown subject {c.subject!r}")
    return out


def _cell(subject: str, category: str, count: int) -> str:
    if count:
        return str(count)
    if (subject, category) in report.NOT_APPLICABLE:
        return NOT_APPLICABLE
    return NOT_TESTED


def anchor(subject: str) -> str:
    """GitHub's heading anchor: lower case, spaces to hyphens, other
    punctuation dropped."""
    kept = "".join(ch for ch in subject.lower() if ch.isalnum() or ch in " -_")
    return kept.replace(" ", "-")


def build(checks: list[Check]) -> str:
    bad = problems(checks)
    if bad:
        raise ValueError("\n".join(bad))
    categories = report.CATEGORY_ORDER
    by_subject: dict[str, list[Check]] = {s: [] for s in report.SUBJECTS}
    for c in checks:
        by_subject[c.subject].append(c)

    out = [GENERATED_NOTE, "# Forensic test coverage\n\n"]
    out.append(
        "Which forensic checks exist for each part of Crush: the sources it opens, the "
        "filesystems it reads in a disk image, the file formats it parses and its decoding "
        "tools. This page lists what is checked, not whether the checks pass — every release "
        "runs them on Linux, macOS and Windows and attaches the results as the "
        f"[forensic audit report]({REPORT_URL}).\n\n"
        "A check runs on committed reference files or on files the test creates. It shows "
        "that Crush behaves as described for those files, not for every possible input.\n\n"
        f"In the tables, a number is how many checks exist; **{NOT_TESTED}** means there is "
        f"no check in that category; **{NOT_APPLICABLE}** means the category doesn't apply "
        "(the reason is given under the part).\n\n"
    )

    out.append("## Categories\n\n")
    for cat in categories:
        out.append(f"- **{cat}** — {report.CATEGORY_INTROS[cat]}\n")
    out.append("\n")

    out.append(f"## Overview\n\n{len(checks)} checks in total.\n\n")
    for group, subjects in report.SUBJECT_GROUPS.items():
        out.append(f"### {group}\n\n")
        out.append("| | " + " | ".join(categories) + " |\n")
        out.append("|---|" + "---|" * len(categories) + "\n")
        for subject in subjects:
            counts = {cat: 0 for cat in categories}
            for c in by_subject[subject]:
                counts[c.category] += 1
            cells = [_cell(subject, cat, counts[cat]) for cat in categories]
            out.append(f"| [{subject}](#{anchor(subject)}) | " + " | ".join(cells) + " |\n")
        out.append("\n")

    out.append("## Checks\n\n")
    for group, subjects in report.SUBJECT_GROUPS.items():
        out.append(f"### {group}\n\n")
        for subject in subjects:
            out.append(f"#### {subject}\n\n")
            subject_checks = by_subject[subject]
            if not subject_checks:
                out.append("No forensic checks.\n\n")
                continue
            for cat in categories:
                for c in subject_checks:
                    if c.category == cat:
                        link = f"[{Path(c.path).name}](../../{c.path})"
                        out.append(f"- **{cat}** — {c.desc} ({link}, `{c.name}`)\n")
            reasons = {
                cat: report.NOT_APPLICABLE[(subject, cat)]
                for cat in categories if (subject, cat) in report.NOT_APPLICABLE
            }
            covered = {c.category for c in subject_checks}
            missing = [cat for cat in categories if cat not in covered and cat not in reasons]
            if missing:
                out.append(f"- *{NOT_TESTED.capitalize()}:* " + ", ".join(missing) + "\n")
            for cat, reason in reasons.items():
                out.append(f"- *{NOT_APPLICABLE}:* {cat} — {reason}\n")
            out.append("\n")
    return "".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Maintain the forensic test coverage page.")
    parser.add_argument("command", choices=["build", "check"])
    args = parser.parse_args(argv)
    try:
        text = build(collect())
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 1
    if args.command == "build":
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current != text:
        print(f"{OUTPUT.relative_to(ROOT)} is out of date -- run: "
              "python scripts/forensic_coverage.py build", file=sys.stderr)
        return 1
    print("up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
