#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 - now Marco Neumann (kalink0)
"""Maintain the user handbook, kept as one file per section so each can be
translated -- and noticed as outdated -- on its own.

    python scripts/handbook.py build            regenerate crush/docs/handbook.md
    python scripts/handbook.py check            links and anchors, every language
    python scripts/handbook.py status [LANG]    per section: missing / outdated / current
    python scripts/handbook.py stamp LANG FILE  record which English a translation is from

Layout (crush/docs/handbook/):
    en/index.md     the title and the ordered list of section files -- the
                    only place that sets the order
    en/<name>.md    one section: an H2, or an H3 of "Viewer Tabs" (one per
                    viewer). The English original; edit the handbook here.
    <lang>/...      a translation, same file names. A file that isn't there
                    yet is read from en/.

build   writes crush/docs/handbook.md: every English section in index
        order, as one page (searchable in one go). Links between section
        files become #anchors again. test_handbook fails while it is out
        of date, so after editing a section just run build.
check   every link to another section file or an #anchor points to
        something that exists -- in each language: a translated heading
        has a different anchor than the English one.
stamp   a translated file starts with `<!-- source_hash: ... -->`, the hash
        of the English file it was translated from. stamp writes it once
        the translation is done; status compares it with the English file
        now, so a section whose English changed shows as outdated.

The handbook's progress is its own: whether a language is offered under
View → Language (90 %) depends only on the application's catalog
(scripts/i18n.py), never on how much of the handbook is translated.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "crush" / "docs"
HANDBOOK_DIR = DOCS / "handbook"
OUTPUT = DOCS / "handbook.md"
SOURCE = "en"
INDEX = "index.md"

GENERATED_NOTE = (
    "<!-- Generated by `python scripts/handbook.py build` from crush/docs/handbook/en/ "
    "-- edit the section files there, not this file. -->\n"
)
_HASH_RE = re.compile(r"\A<!-- source_hash: ([0-9a-f]+) -->\n")
_INDEX_ITEM_RE = re.compile(r"^\s*- \[[^\]]+\]\(([\w-]+\.md)\)\s*$")
_HEADING_RE = re.compile(r"^(#{1,6}) +(.+?) *#*$")
_FENCE_RE = re.compile(r"^ {0,3}(```|~~~)")
# The target of an inline link: ](target)
_LINK_RE = re.compile(r"\]\(([^()\s]+)\)")
_SECTION_LINK_RE = re.compile(r"^([\w-]+\.md)(?:#([\w-]+))?$")


# -- Markdown basics ----------------------------------------------------------------

def _outside_fences(text: str) -> list[tuple[int, str]]:
    """(line number, line) of every line not inside a fenced code block."""
    out = []
    fence: str | None = None
    for i, line in enumerate(text.split("\n")):
        m = _FENCE_RE.match(line)
        if m:
            if fence is None:
                fence = m.group(1)
            elif m.group(1) == fence:
                fence = None
            continue
        if fence is None:
            out.append((i, line))
    return out


def headings(text: str) -> list[tuple[int, int, str]]:
    """(line number, level, text) of every heading outside code blocks."""
    found = []
    for i, line in _outside_fences(text):
        m = _HEADING_RE.match(line)
        if m:
            found.append((i, len(m.group(1)), m.group(2)))
    return found


def base_anchor(heading: str) -> str:
    """GitHub's anchor for a heading: lower case, punctuation dropped
    (letters of any script, digits, '_' and '-' stay), spaces become '-'."""
    return re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")


def anchors(text: str, seen: dict[str, int] | None = None) -> list[str]:
    """The anchors of *text*'s headings in order; a repeated one gets -1,
    -2, ... (*seen* carries the count across files for one page)."""
    seen = {} if seen is None else seen
    out = []
    for _i, _level, heading in headings(text):
        base = base_anchor(heading)
        n = seen.get(base, 0)
        seen[base] = n + 1
        out.append(base if n == 0 else f"{base}-{n}")
    return out


def _normalized(text: str) -> str:
    return text.replace("\r\n", "\n")


def source_hash(text: str) -> str:
    """Hash of an English file; line endings don't count (a Windows checkout
    must not make every translation look outdated)."""
    return hashlib.sha256(_normalized(text).encode("utf-8")).hexdigest()[:16]


def strip_hash(text: str) -> tuple[str | None, str]:
    """(recorded source hash or None, the text without that line)."""
    text = _normalized(text)
    m = _HASH_RE.match(text)
    return (m.group(1), text[m.end():]) if m else (None, text)


# -- The handbook ---------------------------------------------------------------------

class Handbook:
    def __init__(self, directory: Path = HANDBOOK_DIR) -> None:
        self.directory = directory

    def languages(self) -> list[str]:
        return sorted(
            p.name for p in self.directory.iterdir() if p.is_dir() and p.name != SOURCE
        )

    def _read(self, lang: str, name: str) -> str | None:
        path = self.directory / lang / name
        return strip_hash(path.read_text(encoding="utf-8"))[1] if path.is_file() else None

    def index(self, lang: str = SOURCE) -> str:
        text = self._read(lang, INDEX)
        return text if text is not None else self.english(INDEX)

    def english(self, name: str) -> str:
        text = self._read(SOURCE, name)
        if text is None:
            raise FileNotFoundError(self.directory / SOURCE / name)
        return text

    def sections(self) -> list[str]:
        """Section file names in handbook order (from en/index.md)."""
        return [
            m.group(1)
            for line in self.english(INDEX).split("\n")
            if (m := _INDEX_ITEM_RE.match(line))
        ]

    def text(self, lang: str, name: str) -> str:
        """A section in *lang*, or the English one where there is none yet."""
        text = self._read(lang, name)
        return text if text is not None else self.english(name)

    def build(self) -> str:
        """The whole English handbook as one page."""
        index = self.english(INDEX)
        header = index.split("\n- [", 1)[0].rstrip("\n") + "\n\n"
        names = self.sections()
        seen: dict[str, int] = {}
        page_anchor: dict[tuple[str, str], str] = {}
        for name in names:
            text = self.english(name)
            for local, page in zip(anchors(text), anchors(text, seen)):
                page_anchor[(name, local)] = page

        def rewrite(name: str, target: str) -> str:
            if target.startswith("#"):
                return "#" + page_anchor.get((name, target[1:]), target[1:])
            m = _SECTION_LINK_RE.match(target)
            if not m or m.group(1) not in names:
                return target
            other = m.group(1)
            local = m.group(2) or anchors(self.english(other))[0]
            return "#" + page_anchor.get((other, local), local)

        parts = [GENERATED_NOTE, header]
        for name in names:

            def link(m: re.Match[str], name: str = name) -> str:
                return f"]({rewrite(name, m.group(1))})"

            parts.append(_LINK_RE.sub(link, self.english(name)))
        return "".join(parts)

    def check(self) -> list[str]:
        """Broken links, missing or unlisted files -- for every language."""
        problems = []
        names = self.sections()
        english_files = {p.name for p in (self.directory / SOURCE).glob("*.md")}
        for name in names:
            if name not in english_files:
                problems.append(f"{SOURCE}/{INDEX} lists {name}, which doesn't exist")
        for name in sorted(english_files - set(names) - {INDEX}):
            problems.append(f"{SOURCE}/{name} is not listed in {SOURCE}/{INDEX}")
        for lang in [SOURCE, *self.languages()]:
            if lang != SOURCE:
                for p in sorted((self.directory / lang).glob("*.md")):
                    if p.name not in english_files:
                        problems.append(f"{lang}/{p.name} has no English original")
                listed = [
                    m.group(1) for line in self.index(lang).split("\n")
                    if (m := _INDEX_ITEM_RE.match(line))
                ]
                if listed != names:
                    problems.append(f"{lang}/{INDEX} doesn't list the sections of {SOURCE}/{INDEX}")
            file_anchors = {n: set(anchors(self.text(lang, n))) for n in names}
            for name in [INDEX, *names]:
                text = self.index(lang) if name == INDEX else self.text(lang, name)
                for i, line in _outside_fences(text):
                    for target in _LINK_RE.findall(line):
                        problem = _link_problem(target, name, names, file_anchors)
                        if problem:
                            problems.append(f"{lang}/{name}:{i + 1}: {target} -- {problem}")
        return problems

    def status(self, lang: str) -> dict[str, str]:
        """Per file: 'missing', 'unstamped', 'outdated' or 'current'."""
        out = {}
        for name in [INDEX, *self.sections()]:
            path = self.directory / lang / name
            if not path.is_file():
                out[name] = "missing"
                continue
            recorded, _ = strip_hash(path.read_text(encoding="utf-8"))
            if recorded is None:
                out[name] = "unstamped"
            elif recorded != source_hash(self.english(name)):
                out[name] = "outdated"
            else:
                out[name] = "current"
        return out

    def stamp(self, lang: str, name: str) -> None:
        if lang == SOURCE:
            raise ValueError("the English files are the originals; only translations are stamped")
        path = self.directory / lang / name
        _old, text = strip_hash(path.read_text(encoding="utf-8"))
        line = f"<!-- source_hash: {source_hash(self.english(name))} -->\n"
        path.write_text(line + text, encoding="utf-8")


def _link_problem(
    target: str, name: str, names: list[str], file_anchors: dict[str, set[str]]
) -> str | None:
    if target.startswith("#"):
        if name == INDEX or target[1:] not in file_anchors[name]:
            return "no such heading in this file"
        return None
    m = _SECTION_LINK_RE.match(target)
    if not m:
        return None  # an external link or a file outside the handbook
    other, anchor = m.group(1), m.group(2)
    if other not in names:
        return "no such section file"
    if anchor and anchor not in file_anchors[other]:
        return f"no such heading in {other}"
    return None


# -- Command line ---------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Maintain the user handbook's sections.")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("build", help="regenerate crush/docs/handbook.md from the English sections")
    sub.add_parser("check", help="check links and anchors in every language")
    status = sub.add_parser("status", help="which translated sections are missing or outdated")
    status.add_argument("languages", nargs="*")
    stamp = sub.add_parser("stamp", help="record the English a translated file is from")
    stamp.add_argument("language")
    stamp.add_argument("files", nargs="+")
    args = parser.parse_args(argv)
    handbook = Handbook()

    if args.command == "build":
        OUTPUT.write_text(handbook.build(), encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(handbook.sections())} sections)")
        return 0
    if args.command == "check":
        problems = handbook.check()
        print("\n".join(problems) or "no problems")
        return 1 if problems else 0
    if args.command == "status":
        for lang in args.languages or handbook.languages():
            result = handbook.status(lang)
            done = sum(1 for s in result.values() if s == "current")
            print(f"{lang}: {done}/{len(result)} current")
            for name, state in result.items():
                if state != "current":
                    print(f"  {state:9}  {name}")
        return 0
    for name in args.files:
        handbook.stamp(args.language, Path(name).name)
        print(f"stamped {args.language}/{Path(name).name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
